### ISSUE TITLE
Vault timer doesnt start

### ISSUE THREAD

**Issue by pikapikafail** [Iskallia/Vault-public-S1#121]
Single player world issues
Vaults
When you enter a vault it doesn't start the timer. This is the level 0 vault. Also when you leave the vault you don't get any lvls for doing it. The mobs have swords in the off hands. I had skeletons in my fault so they shot me and were holding swords. The blaze or blizz things can one shot you right away which seems strange for a lvl 0 vault.

Vault alters 
After going to the end and back to get ender pearls for the alter it, eat all of the pearls but the number didn't go down. I had to log out and log back in for it to start counting again. I am also playing this with my wife and we can't have 2 separate alters. It will so the same things needed for both. That being said only one of us can see what is needed for the alters. It switches back and forth. It doesn't matter who places it, it randomly can be seen by one of us.

**Comment by BONNe** [comment]
Apparently, you are using 1.0.0 version.

The timer is solved in 1.0.1 version.

**Comment by pikapikafail** [comment]
> Apparently, you are using 1.0.0 version.
> 
> The timer is solved in 1.0.1 version.

How do I download that version? I downloaded the most recent one on the Discord this morning

**Comment by BONNe** [comment]
hmm., discord should link to the last version.
Did you updated or it is a new setup?

**Comment by bmemike** [comment]
You can get the mod (not the modpack) on CF and use that to update your local copy: https://www.curseforge.com/minecraft/mc-mods/vault-hunters-official-mod

**Comment by Braindeado00o** [comment]
@bmemike 
Hi i just downloaded it but got the same JAVA error like 3 days ago. Cant open the JAR

**Comment by bmemike** [comment]
You shouldn't be trying to open the JAR. Save the file from CF. Then copy it into the mods folder in your world instance and remove the old one. 

The new one has a name like the_vault-1.0.1-public.jar and the old one should be the_vault-1.0.0-public.jar

You only want one "the_vault" jar in that directory.

**Comment by Braindeado00o** [comment]
I did use multimc because the modpack was not released. So there is no modpack the instances. 


Von meinem iPhone gesendet

**Comment by pikapikafail** [comment]
Thanks for telling me it was on the website. I believe I have fixed it now. I didn't know there was a fix on the curse website vs the program... I am not a minecraft wizard so it wasn't made clear enough for me I suppose

**Comment by Braindeado00o** [comment]
Von meinem iPhone gesendet

**Comment by Braindeado00o** [comment]
Ah i think I got it. I removed 1.0.0 from multimc and copied the 1.0.1 into it. 
But it still does not run on curseforge I suppose?

**Comment by pikapikafail** [comment]
> You can get the mod (not the modpack) on CF and use that to update your local copy: https://www.curseforge.com/minecraft/mc-mods/vault-hunters-official-mod

Ok so I got the timer running but now I have an issue where my hearts won't come back from food... is that suppose to happen outside of vaults?

**Comment by ImreBoersma** [comment]
Yes, that is supposed to happen. Natural regeneration is disabled in vaults. You'll have to use other ways to regenerate.
